from django.conf.urls import patterns, url

urlpatterns = patterns('imageflow.views',
    url(r'^upload$', 'upload_image', name='upload_image'),
    url(r'^upload/(?P<lightcurve_id>[0-9]+)$', 'upload_image', name='upload_image'),
    url(r'^analysis/(?P<pk>[0-9]+)$', 'astrometry', name='astrometry'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_datetime$', 'set_datetime', name='set_datetime'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_filter_band$', 'set_filter_band', name='set_filter_band'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_latitude$', 'set_latitude', name='set_latitude'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_longitude$', 'set_longitude', name='set_longitude'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_elevation$', 'set_elevation', name='set_elevation'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_target_point_source$', 'set_target_point_source', name='set_target_point_source'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_second_order_extinction$', 'set_second_order_extinction', name='set_second_order_extinction'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_color_index_manual$', 'set_color_index_manual', name='set_color_index_manual'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_color_index_1$', 'set_color_index_1', name='set_color_index_1'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_color_index_2$', 'set_color_index_2', name='set_color_index_2'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_image_companion$', 'set_image_companion', name='set_image_companion'),
    url(r'^analysis/(?P<pk>[0-9]+)/set_reduction_status$', 'set_reduction_status', name='set_reduction_status'),
    url(r'^analysis/(?P<pk>[0-9]+)/get_reduction_status$', 'get_reduction_status', name='get_reduction_status'),
    url(r'^analysis/(?P<pk>[0-9]+)/photometry_params', 'photometry_params', name='photometry_params'),
    url(r'^analysis/(?P<pk>[0-9]+)/comparison_stars', 'comparison_stars', name='comparison_stars'),
    url(r'^analysis/(?P<pk>[0-9]+)/status', 'analysis_status', name='analysis_status'),
    url(r'^analysis/(?P<pk>[0-9]+)/notes$', 'notes', name='notes'),
    url(r'^analysis/astrometry/(?P<pk>[0-9]+)$', 'astrometry', name='astrometry'),
    url(r'^analysis/point_sources/(?P<pk>[0-9]+)$', 'point_sources', name='point_sources'),
    url(r'^analysis/reference_stars/(?P<pk>[0-9]+)$', 'reference_stars', name='reference_stars'),
    url(r'^analysis/comparison_image/(?P<pk>[0-9]+)$', 'comparison_image', name='comparison_image'),
    url(r'^analysis/reduction/(?P<pk>[0-9]+)$', 'reduction', name='reduction'),
    url(r'^api/analysis/(?P<pk>[0-9]+)/results$', 'api_get_analysis_results', name='api_get_analysis_results'),
    url(r'^$', 'index', name='index'),
)
