# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photometry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LightCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_image_filter_set', to='photometry.ImageFilter')),
                ('magband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_magband_set', to='photometry.ImageFilter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
