# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-09 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurve',
            name='magband',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_magband_set', to='photometry.ImageFilter'),
        ),
    ]
