# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightcurve',
            name='image_filter',
        ),
    ]
