# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0002_auto_20180118_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurve',
            name='magband',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_magband_set', to='photometry.ImageFilter'),
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
