# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0003_lightcurve_ciband'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightCurveReduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_order_extinction', models.FloatField(default=0)),
                ('tf', models.FloatField(null=True)),
                ('tf_std', models.FloatField(null=True)),
                ('tf_graph_url', models.CharField(max_length=1024, null=True)),
                ('zpf', models.FloatField(null=True)),
                ('color_index_manual', models.FloatField(null=True)),
                ('hidden_transform', models.FloatField(null=True)),
                ('hidden_transform_intercept', models.FloatField(null=True)),
                ('hidden_transform_std', models.FloatField(null=True)),
                ('hidden_transform_rval', models.FloatField(null=True)),
                ('hidden_transform_graph_url', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lightcurve',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('REDUCTION_PENDING', 'Reduction pending'), ('REDUCTION_COMPLETE', 'Reduction complete')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='lightcurvereduction',
            name='lightcurve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve'),
        ),
    ]
