# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0004_auto_20180310_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurvereduction',
            name='lightcurve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve'),
        ),
    ]
