# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 20:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0005_auto_20180310_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='comparison_star_designations',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
