# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 21:07
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0006_lightcurve_comparison_star_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='common_star_designations',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
