# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0001_initial'),
        ('lightcurve', '0007_lightcurve_common_star_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='filter',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_filter_set', to='photometry.ImageFilter'),
        ),
    ]
