# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-10 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0009_lightcurvereduction_target_color_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightcurvereduction',
            old_name='target_color_index',
            new_name='color_index',
        ),
    ]
