# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0010_auto_20180310_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightcurve',
            old_name='common_star_designations',
            new_name='common_stars',
        ),
        migrations.AlterField(
            model_name='lightcurve',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PHOTOMETRY_PENDING', 'Photometry pending'), ('REDUCTION_PENDING', 'Reduction pending'), ('REDUCTION_COMPLETE', 'Reduction complete')], default='CREATED', max_length=50),
        ),
    ]
