# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0011_auto_20180311_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightcurve',
            old_name='comparison_star_designations',
            new_name='comparison_stars',
        ),
    ]
