# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0012_auto_20180311_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightcurvereduction',
            name='color_index',
            field=models.FloatField(default=0),
        ),
    ]
