# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0013_auto_20180315_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='target_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
