# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0015_lightcurve_photometry_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightcurve',
            name='photometry_settings',
        ),
    ]
