# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-09 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lightcurve', '0001_initial'),
        ('photometry', '__first__'),
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrometry', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASTROMETRY_PENDING', 'Astrometry pending'), ('PHOTOMETRY_PENDING', 'Photometry pending'), ('REVIEW_PENDING', 'Review pending'), ('REDUCTION_COMPLETE', 'Reduction complete'), ('ADDED_TO_LIGHT_CURVE', 'Added to light curve'), ('FAILED', 'Failed')], default='ASTROMETRY_PENDING', max_length=50)),
                ('notes', models.TextField(default='')),
                ('image_datetime', models.DateTimeField(null=True)),
                ('image_jd_corrected', models.FloatField(null=True)),
                ('image_latitude', models.FloatField(default=0)),
                ('image_longitude', models.FloatField(default=0)),
                ('image_elevation', models.FloatField(default=0)),
                ('astrometry_original_display_url', models.CharField(max_length=1024)),
                ('astrometry_annotated_display_url', models.CharField(max_length=1024)),
                ('astrometry_image_fits_url', models.CharField(max_length=1024)),
                ('astrometry_corr_fits_url', models.CharField(max_length=1024)),
                ('coords_plot_url', models.CharField(max_length=1024)),
                ('coords_fits_url', models.CharField(max_length=1024)),
                ('original_display_url', models.CharField(max_length=1024)),
                ('coords', jsonfield.fields.JSONField()),
                ('coords_json_url', models.CharField(max_length=1024)),
                ('psf_scatter_url', models.CharField(max_length=1024)),
                ('psf_bar_url', models.CharField(max_length=1024)),
                ('psf_hist_url', models.CharField(max_length=1024)),
                ('psf_residual_image_url', models.CharField(max_length=1024)),
                ('sigma_clipped_std', models.FloatField(default=0)),
                ('target_name', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(default=0)),
                ('target_x', models.IntegerField(default=-1)),
                ('target_y', models.IntegerField(default=-1)),
                ('image_reference_stars', jsonfield.fields.JSONField()),
                ('image_reference_stars_json_url', models.CharField(max_length=1024)),
                ('catalog_reference_stars', jsonfield.fields.JSONField()),
                ('catalog_reference_stars_json_url', models.CharField(max_length=1024)),
                ('image_unknown_stars', jsonfield.fields.JSONField()),
                ('image_unknown_stars_json_url', models.CharField(max_length=1024)),
                ('annotated_point_sources', jsonfield.fields.JSONField()),
                ('annotated_point_sources_json_url', models.CharField(max_length=1024)),
                ('astrometry_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmissionJob')),
                ('image_filter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photometry.ImageFilter')),
                ('lightcurve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve')),
                ('photometry_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photometry.PhotometrySettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('reduced_stars', jsonfield.fields.JSONField()),
                ('comparison_star_ids', jsonfield.fields.JSONField()),
                ('color_index_manual', models.FloatField(null=True)),
                ('second_order_extinction', models.FloatField(default=0)),
                ('tf', models.FloatField(null=True)),
                ('tf_std', models.FloatField(null=True)),
                ('tf_graph_url', models.CharField(max_length=1024, null=True)),
                ('zpf', models.FloatField(null=True)),
                ('hidden_transform', models.FloatField(null=True)),
                ('hidden_transform_intercept', models.FloatField(null=True)),
                ('hidden_transform_std', models.FloatField(null=True)),
                ('hidden_transform_rval', models.FloatField(null=True)),
                ('hidden_transform_graph_url', models.CharField(max_length=1024, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reduction', to='imageflow.ImageAnalysis')),
                ('color_index_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='photometry.ImageFilter')),
                ('color_index_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='photometry.ImageFilter')),
                ('image_companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserUploadedImage')),
            ],
        ),
    ]
