# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photometry', '0001_initial'),
        ('astrometry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lightcurve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('image_datetime', models.DateTimeField(null=True)),
                ('image_latitude', models.FloatField(default=0)),
                ('image_longitude', models.FloatField(default=0)),
                ('image_elevation', models.FloatField(default=0)),
                ('astrometry_original_display_url', models.CharField(max_length=1024)),
                ('astrometry_annotated_display_url', models.CharField(max_length=1024)),
                ('astrometry_image_fits_url', models.CharField(max_length=1024)),
                ('astrometry_corr_fits_url', models.CharField(max_length=1024)),
                ('coords_plot_url', models.CharField(max_length=1024)),
                ('coords_fits_url', models.CharField(max_length=1024)),
                ('original_display_url', models.CharField(max_length=1024)),
                ('coords', jsonfield.fields.JSONField()),
                ('coords_json_url', models.CharField(max_length=1024)),
                ('psf_scatter_url', models.CharField(max_length=1024)),
                ('psf_bar_url', models.CharField(max_length=1024)),
                ('psf_hist_url', models.CharField(max_length=1024)),
                ('psf_residual_image_url', models.CharField(max_length=1024)),
                ('image_reference_stars', jsonfield.fields.JSONField()),
                ('image_reference_stars_json_url', models.CharField(max_length=1024)),
                ('catalog_reference_stars', jsonfield.fields.JSONField()),
                ('catalog_reference_stars_json_url', models.CharField(max_length=1024)),
                ('astrometry_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmissionJob')),
                ('image_filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photometry.ImageFilter')),
                ('light_curve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('reduced_stars', jsonfield.fields.JSONField()),
                ('second_order_extinction', models.FloatField(default=0)),
                ('tf', models.FloatField(null=True)),
                ('tf_graph_url', models.CharField(max_length=1024, null=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis')),
                ('color_index_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='photometry.ImageFilter')),
                ('color_index_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='photometry.ImageFilter')),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=512)),
                ('astrometry_submission_id', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
