# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('image_datetime', models.DateTimeField(null=True)),
                ('image_latitude', models.FloatField(default=0)),
                ('image_longitude', models.FloatField(default=0)),
                ('image_elevation', models.FloatField(default=0)),
                ('astrometry_original_display_url', models.CharField(max_length=1024)),
                ('astrometry_annotated_display_url', models.CharField(max_length=1024)),
                ('astrometry_image_fits_url', models.CharField(max_length=1024)),
                ('astrometry_corr_fits_url', models.CharField(max_length=1024)),
                ('coords_plot_url', models.CharField(max_length=1024)),
                ('coords_fits_url', models.CharField(max_length=1024)),
                ('original_display_url', models.CharField(max_length=1024)),
                ('coords', jsonfield.fields.JSONField()),
                ('coords_json_url', models.CharField(max_length=1024)),
                ('psf_scatter_url', models.CharField(max_length=1024)),
                ('psf_bar_url', models.CharField(max_length=1024)),
                ('psf_hist_url', models.CharField(max_length=1024)),
                ('psf_residual_image_url', models.CharField(max_length=1024)),
                ('image_reference_stars', jsonfield.fields.JSONField()),
                ('image_reference_stars_json_url', models.CharField(max_length=1024)),
                ('catalog_reference_stars', jsonfield.fields.JSONField()),
                ('catalog_reference_stars_json_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='CREATED', max_length=50)),
                ('reduced_stars', jsonfield.fields.JSONField()),
                ('second_order_extinction', models.FloatField(default=0)),
                ('tf', models.FloatField(null=True)),
                ('tf_graph_url', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=512)),
                ('original_filename', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis')),
            ],
        ),
    ]
