# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcurve', '0003_auto_20180118_0830'),
        ('imageflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageanalysis',
            old_name='light_curve',
            new_name='lightcurve',
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='lightcurve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='color_index_1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='photometry.ImageFilter'),
        ),
        migrations.AlterField(
            model_name='reduction',
            name='color_index_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='photometry.ImageFilter'),
        ),
    ]
