# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0008_astrometrysubmission_upload_url'),
        ('imageflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astrometry_annotated_display_url', models.CharField(max_length=1024)),
                ('astrometry_image_fits_url', models.CharField(max_length=1024)),
                ('astrometry_corr_fits_url', models.CharField(max_length=1024)),
                ('coords_plot_url', models.CharField(max_length=1024)),
                ('coords_fits_url', models.CharField(max_length=1024)),
                ('coords_json_url', models.CharField(max_length=1024)),
                ('psf_scatter_url', models.CharField(max_length=1024)),
                ('psf_bar_url', models.CharField(max_length=1024)),
                ('psf_hist_url', models.CharField(max_length=1024)),
                ('psf_residual_image_url', models.CharField(max_length=1024)),
                ('astrometry_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmissionJob')),
            ],
        ),
    ]
