# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0002_analysisresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
