# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-09 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0002_auto_20180309_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis1_set', to='imageflow.ImageAnalysis')),
                ('analysis2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis2_set', to='imageflow.ImageAnalysis')),
            ],
        ),
    ]
