# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0002_auto_20180118_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedimage',
            name='original_filename',
            field=models.CharField(default='blcam_placeholder.fit', max_length=512),
            preserve_default=False,
        ),
    ]
