# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0003_useruploadedimage_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='uploaded_image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='imageflow.UserUploadedImage'),
            preserve_default=False,
        ),
    ]
