# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-29 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageflow', '0004_useruploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='astrometry_submission_id',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
