# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0001_initial'),
        ('imageflow', '0005_auto_20180119_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadedimage',
            name='astrometry_submission_id',
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmission'),
        ),
    ]
