# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0005_auto_20180201_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='companion_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.UserUploadedImage'),
        ),
    ]
