# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0005_auto_20170529_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='reference_stars_json_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
