# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0006_auto_20180120_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis'),
        ),
    ]
