# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-11 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0006_remove_reduction_comparison_star_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduction',
            name='color_index_1',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='color_index_2',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='color_index_manual',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='hidden_transform',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='hidden_transform_graph_url',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='hidden_transform_intercept',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='hidden_transform_rval',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='hidden_transform_std',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='second_order_extinction',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='tf',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='tf_graph_url',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='tf_std',
        ),
        migrations.RemoveField(
            model_name='reduction',
            name='zpf',
        ),
    ]
