# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-07 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0006_reduction_companion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reduction',
            old_name='companion_image',
            new_name='image_companion',
        ),
    ]
