# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-07 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0007_auto_20180207_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
