# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0007_auto_20180120_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadedimage',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis'),
        ),
        migrations.AlterField(
            model_name='useruploadedimage',
            name='lightcurve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve'),
        ),
        migrations.AlterField(
            model_name='useruploadedimage',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmission'),
        ),
    ]
