# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0008_auto_20180120_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='image_filter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photometry.ImageFilter'),
        ),
    ]
