# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-16 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0008_remove_reduction_image_companion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='target_name',
        ),
    ]
