# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0009_auto_20180207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='zpf',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
    ]
