# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-25 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0009_analysisresult_astrometry_original_display_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='original_display_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
