# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0010_imageanalysis_image_jd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='photometry_settings',
        ),
    ]
