# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0010_auto_20180210_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='tf_std',
            field=models.FloatField(null=True),
        ),
    ]
