# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-25 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0010_analysisresult_original_display_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 25, 19, 17, 15, 867476)),
            preserve_default=False,
        ),
    ]
