# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0001_initial'),
        ('imageflow', '0011_remove_imageanalysis_photometry_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='photometry_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photometry.PhotometrySettings'),
        ),
    ]
