# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-25 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0011_analysisresult_image_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
