# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0012_auto_20180210_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='hidden_transform_intercept',
            field=models.FloatField(null=True),
        ),
    ]
