# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0013_reduction_hidden_transform_intercept'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='starfind_mean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='starfind_median',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='starfind_std',
            field=models.FloatField(default=0),
        ),
    ]
