# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-26 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0013_auto_20170625_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
