# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-11 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0014_auto_20180211_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageanalysis',
            old_name='starfind_mean',
            new_name='sigma_clipped_mean',
        ),
        migrations.RenameField(
            model_name='imageanalysis',
            old_name='starfind_median',
            new_name='sigma_clipped_median',
        ),
        migrations.RenameField(
            model_name='imageanalysis',
            old_name='starfind_std',
            new_name='sigma_clipped_std',
        ),
    ]
