# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0015_analysisresult_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('survey', models.CharField(max_length=512)),
                ('range_min_nm', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='filter_name',
            field=models.CharField(default='B', max_length=1024),
        ),
    ]
