# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0015_auto_20180211_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
