# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0002_photometrysettings'),
        ('imageflow', '0016_imageanalysis_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='photometry_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photometry.PhotometrySettings'),
        ),
    ]
