# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-26 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0017_auto_20170626_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='filter_name',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='image_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageFilter'),
        ),
    ]
