# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0017_imageanalysis_photometry_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Astrometry pending'), ('REVIEW_PENDING', 'Review pending'), ('REVIEW_PENDING', 'Review complete'), ('REDUCTION_COMPLETE', 'Reduction complete'), ('ADDED_TO_LIGHT_CURVE', 'Added to light curve'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
