# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0019_auto_20170629_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_elevation_m',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='image_latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='image_longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
