# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0019_auto_20180213_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='status',
            field=models.CharField(choices=[('ASTROMETRY_PENDING', 'Astrometry pending'), ('PHOTOMETRY_PENDING', 'Photometry pending'), ('REVIEW_PENDING', 'Review pending'), ('REVIEW_PENDING', 'Review complete'), ('REDUCTION_COMPLETE', 'Reduction complete'), ('ADDED_TO_LIGHT_CURVE', 'Added to light curve'), ('FAILED', 'Failed')], default='ASTROMETRY_PENDING', max_length=50),
        ),
    ]
