# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0020_auto_20171017_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image_elevation_m',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image_longitude',
            field=models.FloatField(default=0),
        ),
    ]
