# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-16 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0021_auto_20180214_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='sigma_clipped_mean',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='sigma_clipped_median',
        ),
    ]
