# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0021_auto_20171017_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='image_elevation_m',
            new_name='image_elevation',
        ),
    ]
