# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 20:34
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0022_auto_20171017_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='reference_stars_with_airmass',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
