# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 05:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0022_auto_20180216_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='comparison_stars',
            field=jsonfield.fields.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
