# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0023_analysisresult_reference_stars_with_airmass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='reference_stars',
            new_name='image_reference_stars',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='reference_stars_json_url',
            new_name='image_reference_stars_json_url',
        ),
    ]
