# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-18 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0023_reduction_comparison_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reduction',
            old_name='comparison_stars',
            new_name='comparison_star_ids',
        ),
    ]
