# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-19 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0024_auto_20180218_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduction',
            name='color_index_manual',
            field=models.FloatField(null=True),
        ),
    ]
