# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0024_auto_20171017_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='color_index_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='imageflow.ImageFilter'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='color_index_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='imageflow.ImageFilter'),
        ),
    ]
