# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-18 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0025_auto_20171018_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='color_index_1',
            field=models.ForeignKey(default='B', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='imageflow.ImageFilter'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='color_index_2',
            field=models.ForeignKey(default='V', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='imageflow.ImageFilter'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image_filter',
            field=models.ForeignKey(default='B', null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageFilter'),
        ),
    ]
