# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0026_auto_20171018_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefilter',
            name='urat1_key',
            field=models.CharField(default='Bmag', max_length=50),
            preserve_default=False,
        ),
    ]
