# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-21 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0027_imagefilter_urat1_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='reference_stars_with_airmass',
            new_name='reduced_stars',
        ),
    ]
