# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-28 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0027_imageanalysis_image_jd_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='target_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
