# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0028_auto_20171021_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='transformation_coefficient',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='transformation_coefficient_graph_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
