# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-09 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageflow', '0029_auto_20171025_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('reduced_stars', jsonfield.fields.JSONField()),
                ('transformation_coefficient', models.FloatField()),
                ('transformation_coefficient_graph_url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='color_index_1',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='color_index_2',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='reduced_stars',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='transformation_coefficient',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='transformation_coefficient_graph_url',
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageFilter'),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='band',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='reduction',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageflow.AnalysisResult'),
        ),
        migrations.AddField(
            model_name='reduction',
            name='color_index_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_1_set', to='imageflow.ImageFilter'),
        ),
        migrations.AddField(
            model_name='reduction',
            name='color_index_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_color_index_2_set', to='imageflow.ImageFilter'),
        ),
        migrations.AddField(
            model_name='reduction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
