# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-09 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0030_auto_20171209_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reduction',
            name='user',
        ),
    ]
