# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0031_remove_reduction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduction',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imageflow.AnalysisResult'),
        ),
    ]
