# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-10 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0032_auto_20171209_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reduction',
            old_name='transformation_coefficient',
            new_name='tf',
        ),
        migrations.RenameField(
            model_name='reduction',
            old_name='transformation_coefficient_graph_url',
            new_name='tf_graph_url',
        ),
    ]
