# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0033_auto_20171210_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightCurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('image_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_image_filter_set', to='imageflow.ImageFilter')),
                ('magband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightcurve_magband_set', to='imageflow.ImageFilter')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='light_curve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.LightCurve'),
        ),
    ]
