# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-10 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageflow', '0034_auto_20171210_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightcurve',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reduction',
            name='second_order_extinction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
