# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0036_auto_20180114_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
