# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-09 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0002_auto_20180309_0252'),
        ('lightcurve', '0002_auto_20180309_0252'),
        ('astrometry', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedimage',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis'),
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='lightcurve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightcurve.LightCurve'),
        ),
        migrations.AddField(
            model_name='useruploadedimage',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmission'),
        ),
    ]
