# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstrometrySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subid', models.IntegerField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('FAILED_TO_SUBMIT', 'Failed to submit')], default='SUBMITTED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AstrometrySubmissionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astrometry.AstrometrySubmission')),
            ],
        ),
    ]
