# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0002_auto_20160226_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometrysubmission',
            name='succeeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astrometrysubmissionjob',
            name='annotations',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astrometrysubmissionjob',
            name='succeeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
