# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0003_auto_20160226_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrometrysubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='SUBMITTED', max_length=50),
        ),
    ]
