# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0004_auto_20160226_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometrysubmissionjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='astrometrysubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('FAILED_TO_SUBMIT', 'Failed to submit'), ('FAILED_TO_PROCESS', 'Failed to process')], default='SUBMITTED', max_length=50),
        ),
    ]
