# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrometry', '0005_auto_20160226_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrometrysubmissionjob',
            name='jobid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
