# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=512, unique=True)),
                ('system', models.CharField(max_length=512)),
                ('range_min_nm', models.IntegerField()),
                ('urat1_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotometrySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigma_psf', models.FloatField(default=2.0)),
                ('crit_separation', models.FloatField(default=5.0)),
                ('threshold', models.FloatField(default=5.0)),
                ('box_size', models.IntegerField(default=11)),
                ('iters', models.IntegerField(default=1)),
            ],
        ),
    ]
