# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotometrySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigma_psf', models.FloatField(default=2.0)),
                ('crit_separation', models.FloatField(default=5.0)),
                ('threshold', models.FloatField(default=5.0)),
                ('box_size', models.IntegerField(default=11)),
                ('iters', models.IntegerField(default=1)),
            ],
        ),
    ]
