# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageflow', '0012_imageanalysis_photometry_settings'),
        ('photometry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometrysettings',
            name='analysis',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='imageflow.ImageAnalysis'),
            preserve_default=False,
        ),
    ]
