# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilter',
            name='band',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
