# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photometry', '0003_auto_20180325_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometrysettings',
            name='exptime',
            field=models.FloatField(default=1.0),
        ),
    ]
